server:
  port: 8082

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/microservice
    password: 1234abcd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
